import type { Metadata } from 'next';
import Link from 'next/link';
import { Open_Sans } from 'next/font/google';
import './globals.css';

const inter = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Paul',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <menu>
            <li>
              <Link href="todos">Todos</Link>
            </li>
          </menu>
        </nav>
        {children}
      </body>
    </html>
  );
}
